version: 1.0.{build}
os: Unstable
shallow_clone: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: BBBH4QgZXCnE6nFrux34cLWWO5GXrnMU9OZJGJdNePovxJZFzBcm3FsaESNA6zWj
cache:
- build/Version/opencover.snk
- build/Version/opencover.public.snk
- build/Version/build.number
nuget:
  disable_publish_on_pr: true
build_script:
- build create-release
test: off
artifacts:
- path: main/bin/installer/*.msi
  name: Installer
- path: main/bin/nugetpackage/*.nupkg
  name: Nuget
- path: main/bin/zip/*.zip
  name: ZipArchive
- path: main/bin/nugetpackage-rc/*.nupkg
  name: NugetCandidate
deploy:
- provider: NuGet
  api_key:
    secure: yew/4xjmqdUs1U//LNGQjjMgB3JVantsz09C2LxmKaLXuG1gEsWJl+Nd+VRmB3TM
  skip_symbols: true
  artifact: Nuget
  on:
    branch: release
- provider: NuGet
  api_key:
    secure: yew/4xjmqdUs1U//LNGQjjMgB3JVantsz09C2LxmKaLXuG1gEsWJl+Nd+VRmB3TM
  skip_symbols: true
  artifact: NugetCandidate
  on:
    branch: rc
on_success:
- build dogfood-release